# fly.toml app configuration file generated for 1-summer-sea-3563 on 2025-10-15T17:03:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '1-summer-sea-3563'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  # Disable Fly.io proxy content negotiation - pass all requests to app
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[mounts]
  source = "webdiff_data"
  destination = "/app/data"
  initial_size = "3gb"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
