services:
  - type: web
    name: webdiff-comparison-tool
    runtime: node
    buildCommand: |
      npm install
      npx playwright install-deps chromium
      npx playwright install chromium
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: 0
