name: Visual Regression Testing with WebDiff

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: # Allows manual trigger
    inputs:
      production_url:
        description: 'Production URL'
        required: true
        default: 'https://www.rakuten.com'
      preview_url:
        description: 'Preview URL'
        required: true
        default: 'https://preview-www.rakuten.com'

jobs:
  visual-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Visual Comparison
        id: webdiff
        env:
          WEBDIFF_URL: https://1-summer-sea-3563.fly.dev
          PROD_URL: ${{ github.event.inputs.production_url || 'https://www.rakuten.com' }}
          PREVIEW_URL: ${{ github.event.inputs.preview_url || 'https://preview-www.rakuten.com' }}
          AUTH_COOKIES: ${{ secrets.RAKUTEN_AUTH_COOKIES }}
        run: |
          echo "🚀 Starting Visual Comparison..."
          echo "Production: $PROD_URL"
          echo "Preview: $PREVIEW_URL"

          # Call WebDiff API
          RESPONSE=$(curl -s -X POST \
            "$WEBDIFF_URL/api/compare" \
            -H "Content-Type: application/json" \
            -d "{
              \"url1\": \"$PROD_URL\",
              \"url2\": \"$PREVIEW_URL\",
              \"cookies\": $AUTH_COOKIES
            }")

          echo "Response: $RESPONSE"

          # Parse results
          DIFF_COUNT=$(echo $RESPONSE | jq -r '.differenceCount // 0')
          COMPARISON_ID=$(echo $RESPONSE | jq -r '.comparisonId // "unknown"')
          SUCCESS=$(echo $RESPONSE | jq -r '.success // false')

          echo "✅ Comparison complete!"
          echo "📊 Differences found: $DIFF_COUNT"
          echo "🔗 Comparison ID: $COMPARISON_ID"

          # Export for next steps
          echo "diff_count=$DIFF_COUNT" >> $GITHUB_OUTPUT
          echo "comparison_id=$COMPARISON_ID" >> $GITHUB_OUTPUT
          echo "success=$SUCCESS" >> $GITHUB_OUTPUT

      - name: Check Results
        if: steps.webdiff.outputs.success == 'true'
        run: |
          DIFF_COUNT=${{ steps.webdiff.outputs.diff_count }}

          echo "## 🎨 Visual Regression Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Differences Found:** $DIFF_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "**Comparison ID:** ${{ steps.webdiff.outputs.comparison_id }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🔗 View screenshots: https://1-summer-sea-3563.fly.dev/screenshots/${{ steps.webdiff.outputs.comparison_id }}/" >> $GITHUB_STEP_SUMMARY

          # Optional: Fail if too many differences (adjust threshold as needed)
          if [ $DIFF_COUNT -gt 100 ]; then
            echo "⚠️ Warning: More than 100 differences detected!"
            echo "This might indicate a major UI change. Please review carefully."
            # Uncomment to make workflow fail:
            # exit 1
          fi

      - name: Comment on PR
        if: github.event_name == 'pull_request' && steps.webdiff.outputs.success == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const diffCount = '${{ steps.webdiff.outputs.diff_count }}';
            const comparisonId = '${{ steps.webdiff.outputs.comparison_id }}';
            const screenshotUrl = `https://1-summer-sea-3563.fly.dev/screenshots/${comparisonId}/`;

            const body = `## 🎨 Visual Regression Test Results

            **Differences Found:** ${diffCount}

            📸 **Screenshots:**
            - [View URL 1 with highlights](${screenshotUrl}url1_highlighted.png)
            - [View URL 2 with highlights](${screenshotUrl}url2_highlighted.png)

            ${diffCount > 50 ? '⚠️ **Warning:** Significant visual changes detected!' : '✅ Visual changes look reasonable'}

            ---
            🤖 Generated by WebDiff Visual Testing Tool`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-diff-results
          path: |
            *.json
          retention-days: 30
